# _common.R
library(tidyverse)
library(skimr)
library(janitor)
library(GGally)
library(Amelia)
library(patchwork)
library(effsize)
library(nortest)
library(rstatix)
library(car)
library(coin)
library(here)

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache = TRUE)
options(dplyr.summarise.inform = FALSE)
set.seed(123)
